// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApis.Data;

namespace MyApis.Migrations
{
    [DbContext(typeof(MyApisContext))]
    partial class MyApisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BL.Person", b =>
                {
                    b.Property<string>("Aadhaar")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasFace")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHands")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIQ")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLegs")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonGender")
                        .HasColumnType("int");

                    b.HasKey("Aadhaar");

                    b.ToTable("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
